export const SET_CONTACTS_LIST = 'SET_CONTACTS_LIST';
export const SET_SELECTED_CONTACT = 'SET_SELECTED_CONTACT';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
