export const SET_CONTACTS_LIST = 'SET_CONTACTS_LIST';
export const SET_SELECTED_CONTACT = 'SET_SELECTED_CONTACT';
export const EDIT_DETAILS = 'EDIT_DETAILS';
export const END_EDIT_DETAILS = 'END_EDIT_DETAILS';
